// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file densenet121-1.2.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace WinMLPlayground
{
    
    public sealed class DenseNetInput
    {
        public TensorFloat data_0; // shape(1,3,224,224)
    }
    
    public sealed class DenseNetOutput
    {
        public TensorFloat fc6_1; // shape(1,1000,1,1)
    }
    
    public sealed class DenseNetModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<DenseNetModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            DenseNetModel learningModel = new DenseNetModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<DenseNetOutput> EvaluateAsync(DenseNetInput input)
        {
            binding.Bind("data_0", input.data_0);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new DenseNetOutput();
            output.fc6_1 = result.Outputs["fc6_1"] as TensorFloat;
            return output;
        }
    }
}

