// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file squeezenet1.2.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace WinMLPlayground
{
    
    public sealed class SqueezeNetInput
    {
        public TensorFloat data_0; // shape(1,3,224,224)
    }
    
    public sealed class SqueezeNetOutput
    {
        public TensorFloat softmaxout_1; // shape(1,1000,1,1)
    }
    
    public sealed class SqueezeNetModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<SqueezeNetModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            SqueezeNetModel learningModel = new SqueezeNetModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<SqueezeNetOutput> EvaluateAsync(SqueezeNetInput input)
        {
            binding.Bind("data_0", input.data_0);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new SqueezeNetOutput();
            output.softmaxout_1 = result.Outputs["softmaxout_1"] as TensorFloat;
            return output;
        }
    }
}

